---
namespace: "tcharl"
name: "ansible_orchestration"
version: "1.0.1"
description: "Reuses the marvelous geerlingguy's Kubernetes role with some platform's compliant configuration"

authors:
  - "Charlie Mordant <cmordant1@gmail.com>"

repository: "https://github.com/OsgiliathEnterprise/ansible-orchestration"
documentation: "https://github.com/OsgiliathEnterprise/ansible-orchestration/blob/master/README.md"
homepage: "https://github.com/OsgiliathEnterprise/ansible-orchestration"
issues: "https://github.com/OsgiliathEnterprise/ansible-orchestration/issues"

readme: "README.md"
license:
  - "Apache-2.0"
tags:
  - "kubernetes"
