---

- name: Drain-and-reset | drain nodes
  ansible.builtin.command: "kubectl drain {{ hostvars[registeredhost].hostname | default(registeredhost) }} --delete-emptydir-data --force --timeout=800s --ignore-daemonsets=true"
  become: Yes
  failed_when: false
  register: res
  changed_when: res.stdout == "node/{{ hostvars[registeredhost].hostname | default(registeredhost) }} drained"
  loop: "{{ groups[kube_nodes_group] | default([]) | list }}"
  loop_control:
    loop_var: registeredhost

- name: Drain-and-reset | delete nodes at master level
  ansible.builtin.command: "kubectl delete node --all"
  register: res
  changed_when: "'deleted' in res.stdout"
  become: Yes
  failed_when: false

- name: Drain-and-reset | reset kubeadm
  ansible.builtin.command: "kubeadm reset -f"
  register: res
  changed_when: "'[reset]' in res.stdout"
  become: Yes
  failed_when: false
