---

- name: Drain-and-reset | remove charts with disruption budget (istio-ingress)
  kubernetes.core.helm:
    name: istio-ingress
    namespace: istio-system
    release_state: absent
    kubeconfig: "{{ kube_config_path }}"
  become: Yes
  failed_when: false

- name: Drain-and-reset | remove charts with disruption budget (istio-egress)
  kubernetes.core.helm:
    name: istio-egress
    namespace: istio-system
    release_state: absent
    kubeconfig: "{{ kube_config_path }}"
  become: Yes
  failed_when: false

- name: Drain-and-reset | remove charts with disruption budget (istiod)
  kubernetes.core.helm:
    name: istiod
    namespace: istio-system
    release_state: absent
    kubeconfig: "{{ kube_config_path }}"
  become: Yes
  failed_when: false

- name: Drain-and-reset | remove charts with disruption budget (istio-base)
  kubernetes.core.helm:
    name: istio-base
    namespace: istio-system
    release_state: absent
    kubeconfig: "{{ kube_config_path }}"
  become: Yes
  failed_when: false

- name: Drain-and-reset | drain nodes
  kubernetes.core.k8s_drain:
    name: "{{ hostvars[registeredhost].hostname | default(registeredhost) }}"
    state: drain
    force: true
    ignore_daemonsets: true
    delete_emptydir_data: true
    terminate_grace_period: 800
    kubeconfig: "{{ kube_config_path }}"
  become: Yes
  failed_when: false
  loop: "{{ groups[kube_nodes_group] | default([]) | list }}"
  loop_control:
    loop_var: registeredhost

- name: Drain-and-reset | list all nodes for deletion
  kubernetes.core.k8s_info:
    kind: Node
    kubeconfig: "{{ kube_config_path }}"
  become: Yes
  register: _k8s_nodes
  failed_when: false

- name: Drain-and-reset | delete nodes at master level
  kubernetes.core.k8s:
    api_version: v1
    kind: Node
    name: "{{ item.metadata.name }}"
    state: absent
    kubeconfig: "{{ kube_config_path }}"
  become: Yes
  loop: "{{ _k8s_nodes.resources | default([]) }}"
  failed_when: false

- name: Drain-and-reset | reset kubeadm
  ansible.builtin.command: "kubeadm reset -f"
  register: res
  changed_when: "'[reset]' in res.stdout"
  become: Yes
  failed_when: false
