---

- name: Firewall | Include firewalld role for masters
  ansible.builtin.include_role:
    name: tcharl.ansible_routing
  vars:
    firewalld_zones:
      - name: "{{ kube_firewall_zone }}"
        enabled_service:
          - service: "ssh"
          - service: "http"
          - service: "https"
        enabled_ports:
          - port: 6443
            protocol: tcp
          - port: 2379
            protocol: tcp
          - port: 2380
            protocol: tcp
          - port: 10250
            protocol: tcp
          - port: 10259
            protocol: tcp
          - port: 10257
            protocol: tcp
          - port: 179
            protocol: tcp
          - port: 4789
            protocol: udp
  when: kube_masters_group in group_names
  tags:
    - dependency

- name: Firewall | Include firewalld role for nodes
  ansible.builtin.include_role:
    name: tcharl.ansible_routing
  vars:
    firewalld_zones:
      - name: "{{ kube_firewall_zone }}"
        enabled_service:
          - service: "ssh"
        enabled_ports:
          - port: 10250
            protocol: tcp
          - port: 179
            protocol: tcp
          - port: 4789
            protocol: udp
        enabled_port_ranges:
          - port_range: "30000-32767"
            protocol: tcp
  when: kube_nodes_group in group_names
  tags:
    - dependency
