---
- name: Ipa-api-server | Check apiserver cert existence
  ansible.builtin.stat:
    path: "{{ kubernetes_certificates_path }}apiserver.crt"
  register: orchestration_apiservercert
  become: true

# - name: ansible-orchestration | ipa-api-server | Check that the apiserver.crt exists
#  shell: |
#    set -o pipefail && echo '{{ company_realm_password }}' | kinit admin > /dev/null
#    ipa cert-find --ca=kubernetes-ca --subject={{ orchestration_host_hostname }} --exact | grep -c 'Status: VALID'
#  no_log: "{{ secure_logs }}"
#  delegate_to: "{{ groups[idm_group][0] }}"
#  changed_when: False
#  failed_when: False
#  register: ipa_server_cert_valid

- name: Ipa-api-server | configure http service
  freeipa.ansible_freeipa.ipaservice:
    ipaadmin_password: "{{ company_realm_password }}"
    name: "{{ item }}"
    host: "{{ orchestration_host_hostname }}"
    allow_retrieve_keytab_host: "{{ orchestration_host_hostname }}"
    allow_create_keytab_host: "{{ orchestration_host_hostname }}" # TODO create kubernetes master group
    force: True
  delegate_to: "{{ groups[idm_group][0] }}"
  no_log: "{{ secure_logs }}"
  loop:
   - "HTTP/{{ orchestration_host_hostname }}"
  failed_when: false
  changed_when: false

- name: Ipa-api-server | create apiserver certs
  community.crypto.openssl_privatekey:
    path: "{{ kubernetes_certificates_path }}apiserver.key"
  become: true

- name: Ipa-api-server | create kube-apiserver csr
  community.crypto.openssl_csr:
    path: "{{ kubernetes_certificates_path }}apiserver.csr"
    privatekey_path: "{{ kubernetes_certificates_path }}apiserver.key"
    country_name: "{{ kube_credential_country_name }}"
    organization_name: "{{ company_domain }}"
    email_address: "{{ kube_credential_email_address }}"
    common_name: "{{ orchestration_host_hostname }}"
    subject_alt_name: "{{ ['DNS:' + (orchestration_host_hostname), 'IP:' + ((kube_service_cidr | default('10.96.0.0/12')) | ansible.utils.next_nth_usable(1)), 'IP:' + (orchestration_master_ip)] + (kube_alt_names | default([]) | map('regex_replace', '^', 'DNS:') | unique) }}"
    key_usage:
      - digitalSignature
      - keyEncipherment
    extended_key_usage:
      - serverAuth
  when:
   - not orchestration_apiservercert.stat.exists
  become: true

# - name: ansible-orchestration | ipa-api-server | apiserver service to kubernetes adminstrator group
#  freeipa.ansible_freeipa.ipagroup:
#    ipaadmin_password: "{{ company_realm_password }}"
#    name: "kubernetes-administrators"
#    service: "HTTP/api.kubernetes.{{ company_domain }}"
#  no_log: "{{ secure_logs }}"
#  delegate_to: "{{ groups[idm_group][0] }}"
#  when:
#   - not ipa_group_kubeadm_exists.stdout == '1'

- name: Ipa-api-server | request apiserver certificate from IPA
  freeipa.ansible_freeipa.ipacert:
    ipaadmin_password: "{{ company_realm_password }}"
    ca: kubernetes-ca
    principal: "HTTP/{{ orchestration_host_hostname }}"
    csr_file: "{{ kubernetes_certificates_path }}apiserver.csr"
    certificate_out: "{{ kubernetes_certificates_path }}apiserver.crt"
    profile_id: kubeAdministrators
    state: requested
  no_log: "{{ secure_logs }}"
  become: true
