---

- name: ansible-orchestration | kube-destroy | drain nodes
  command: "kubectl drain {{ hostvars[registeredhost].hostname | default(registeredhost) }} --delete-local-data --force --ignore-daemonsets"
  become: Yes
  failed_when: false
  loop: "{{ groups[kube_nodes_group] | default([]) | list }}"
  loop_control:
    loop_var: registeredhost
  when:
    - kube_masters_group in group_names

- name: ansible-orchestration | kube-destroy | delete nodes at master level
  command: "kubectl delete node --all"
  become: Yes
  failed_when: false
  when:
    - kube_masters_group in group_names

- name: ansible-orchestration | kube-destroy | reset kubeadm
  command: "kubeadm reset -f"
  become: Yes
  failed_when: false
  when:
    - kube_masters_group in group_names

- name: ansible-orchestration | kube-destroy | stop kubelet service
  service:
    name: kubelet
    state: stopped
  failed_when: false
  become: Yes

- name: ansible-orchestration | kube-destroy | list files
  ansible.builtin.find:
    paths: "/var/lib/kubelet/pods"
    follow: yes
    file_type: directory
    recurse: false
  register: pod_data_folder_content
  become: Yes

- name: ansible-orchestration | kube-destroy | debug found folders to destroy
  ansible.builtin.debug:
    msg: "{{ pod_data_folder_content }}"
    verbosity: 3

- name: ansible-orchestration | kube-destroy | iterating over the pods
  ansible.builtin.include_tasks: destroy-kubelet-volumes.yml
  loop: "{{ pod_data_folder_content.files | map(attribute='path') }}"
  loop_control:
    loop_var: pod_files

- name: ansible-orchestration | kube-destroy | remove unwanted packages
  package:
    name:
     - kubeadm
     - kubectl
     - kubelet
     - kubernetes-cni
     - kubernetes-client
     - kubernetes-ansible
     - kubernetes-node
     - kubernetes-master
    state: absent
  become: Yes

- name: ansible-orchestration | kube-destroy | Get a list of all running containers
  docker_host_info:
    containers: True
  become: Yes
  register: docker_info

- name: ansible-orchestration | kube-destroy | Debug a list of all running containers
  ansible.builtin.debug:
    msg: "{{ docker_info.containers }}"

- name: ansible-orchestration | kube-destroy | Stop all running containers
  community.docker.docker_container:
    name: '{{ item.Names[0] | regex_replace("^/", "") }}'
    state: absent
  become: Yes
  loop: '{{ docker_info.containers }}'

- name: ansible-orchestration | kube-destroy | Prune everything
  community.docker.docker_prune:
    containers: yes
    images: yes
    networks: yes
    volumes: yes
    builder_cache: yes
  become: Yes

- name: ansible-orchestration | kube-destroy | remove kubernetes configuration folder
  file:
    path: "{{ item }}"
    state: absent
    recurse: yes
  become: Yes
  loop:
    - /etc/cni
    - /etc/kubernetes
    - /etc/sysconfig/kubelet
    - /etc/systemd/system/multi-user.target.wants/kubelet.service
    - /root/.kube
    - /usr/lib/etcd
    - /usr/lib/kubelet
    - /usr/lib/systemd/system/kubelet.service
    - /usr/lib/systemd/system/kubelet.service.d
    - /var/lib/etcd
    - /var/lib/cni
    - /var/lib/kubelet
  failed_when: false

- name: ansible-orchestration | kube-destroy | Just force systemd to reread configs (2.4 and above)
  ansible.builtin.systemd:
    daemon_reload: yes
  become: Yes

- name: ansible-routing | handler | restart-firewall
  service:
    name: firewalld
    state: restarted
  become: yes
