---

- name: Kube-apiserver-kubelet-client | remove kubeadm kubelet-client cert so IPA-signed one is created
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  loop:
    - "{{ kubernetes_certificates_path }}apiserver-kubelet-client.crt"
    - "{{ kubernetes_certificates_path }}apiserver-kubelet-client.key"
    - "{{ kubernetes_certificates_path }}apiserver-kubelet-client.csr"
  become: true

- name: Kube-apiserver-kubelet-client | create kube-apiserver-kubelet-client certs
  community.crypto.openssl_privatekey:
    path: "{{ kubernetes_certificates_path }}apiserver-kubelet-client.key"
  become: true

- name: Kube-apiserver-kubelet-client | create kube-apiserver-kubelet-client csr
  community.crypto.openssl_csr:
    path: "{{ kubernetes_certificates_path }}apiserver-kubelet-client.csr"
    privatekey_path: "{{ kubernetes_certificates_path }}apiserver-kubelet-client.key"
    country_name: "{{ kube_credential_country_name }}"
    organization_name: "system:masters"
    email_address: "{{ kube_credential_email_address }}"
    common_name: "{{ orchestration_host_hostname }}"
    key_usage:
      - digitalSignature
      - keyEncipherment
    extended_key_usage:
      - clientAuth
  become: true

- name: Kube-apiserver-kubelet-client | request kubelet client certificate from IPA
  freeipa.ansible_freeipa.ipacert:
    ipaadmin_password: "{{ company_realm_password }}"
    ca: kubernetes-ca
    principal: "host/{{ orchestration_host_hostname }}"
    csr_file: "{{ kubernetes_certificates_path }}apiserver-kubelet-client.csr"
    certificate_out: "{{ kubernetes_certificates_path }}apiserver-kubelet-client.crt"
    profile_id: kubeAdministrators
    state: requested
  no_log: "{{ secure_logs }}"
  become: true
