---

- name: Nfs-mountpoints | process each server group
  ansible.builtin.include_tasks: _server-inner.yml
  loop: "{{ nfs_mountpoints | default([]) }}"
  when: item.mountpoints is defined
  vars:
    _outer_server_group: "{{ item }}"
