---

- name: Nfs-mountpoints | create persistent volume for enriched item
  ansible.builtin.include_tasks: persistent-volume.yml
  vars:
    nfs_mountpoint: "{{ _pv_item.nfs_mountpoint }}"
    kube_volume_to_mount: "{{ _pv_item.kube_volume_to_mount }}"