---
- name: ansible-orchestration | persistent-volume | create temp directory to host template
  changed_when: false
  ansible.builtin.tempfile:
    state: directory
    suffix: pv
  delegate_to: "{{ groups['kube_master'][0] }}"
  register: persistent_volumes_temp_directory

- name: ansible-orchestration | persistent-volume | create persistent volume file
  ansible.builtin.template:
    src: persistent-volume.yml.j2
    dest: "{{ persistent_volumes_temp_directory.path }}/pv.yml"
    owner: root
    group: root
    mode: '0600'
  when:  kube_volume_to_mount.volume_kind == 'Hardwire'
  delegate_to: "{{ groups['kube_master'][0] }}"
  become: true

- name: ansible-volumes | install prerequisite - docker
  pip:
    name: kubernetes
    state: present
  delegate_to: "{{ groups['kube_master'][0] }}"
  become: true

- name: ansible-orchestration | persistent-volume | execute kubectl apply # TODO replace by CSI storage
  community.kubernetes.k8s:
    state: present
    src: "{{ persistent_volumes_temp_directory.path }}/pv.yml"
    ca_cert: "{{ kube_cacert_path | default(omit) }}"
    client_cert: "{{ kube_sysadmin_client_cert_path | default(omit) }}"
    client_key: "{{ kube_sysadmin_client_key_path | default(omit) }}"
    kubeconfig: "{{ kube_config_path }}"
    context: "{{ kube_context | default('kubernetes-admin@kubernetes') }}"
  delegate_to: "{{ groups['kube_master'][0] }}"
  when:  kube_volume_to_mount.volume_kind == "Hardwire"
  become: true
