---

- name: Prereq | Install needed package
  ansible.builtin.package:
    name:
     - iproute-tc
     - python3-pip
     - python3-pyOpenSSL
     - python3-cryptography
     - wget
    state: present
  become: true

- name: Prereq | remove unwanted packages
  ansible.builtin.package:
    name:
     - zram-generator-defaults
    state: absent
  become: true

- name: Prereq | install prereq
  ansible.builtin.pip:
    name: kubernetes
  become: true

- name: Prereq | ensure swap disabled
  ansible.builtin.command: "swapoff --all"
  changed_when: False
  become: true
