---

- name: ansible-orchestration | service-mesh | create istio-system namespace
  ansible.builtin.include_role:
    name: tcharl.ansible_orchestration_cli
  vars:
    ansible_become: true
    standalone_role: False
    kube_sysadmin_client_cert_path: "{{ kube_credential_folder }}/kubeadm.crt"
    kube_sysadmin_client_key_path: "{{ kube_credential_folder }}/kubeadm.pem"
    kube_cacert_path: "{{ kubernetes_certificates_path }}ca.crt"
    descriptor_sets:
      - url: https://github.com/OsgiliathEnterprise/orchestrator-system-configuration.git
        kind: git
        branch: master
        descriptors:
          - namespaces/kubernetes-ns.yml
    helm_install: False
