---
# handlers file for ansible-orchestration
- name: ansible-orchestration | refresh kube
  systemd:
    state: restarted
    daemon_reload: yes
    name: kubelet
  become: true
  listen: ansible-orchestration | refresh kube
