---
- name: Prepare-VMs
  hosts: all
  vars:
    manage_lvm: true
    lvm_groups:
      - vgname: non-persistent
        disks:
          - /dev/sdb1
        create: true
    libvirt_host_pools:
      - name: libvirt_vg
        type: lvm2
        source: non-persistent
    libvirt_host_networks:
      - name: default
        mode: nat
        bridge: vibr0
        ip: 192.168.122.1
        netmask: 255.255.255.0
        dhcp_start: 192.168.122.10
        dhcp_end: 192.168.122.200
    users_group_list:
      - name: libvirt
    systemusers_user_list:
      - name: libvirt
        group: libvirt
        groups: wheel
    virtualization_guest_boxes:
      - name: fedoraKubeMasterVM
        url: https://vagrantcloud.com/tcharl/boxes/fedora-31-cgroupv1/versions/1.0.0/providers/libvirt.box
        memory_mb: 1548
        vcpus: 1
        ssh_port_on_host: 22022
        # same as the one in molecule.yml
        ansible_groups:
          - kube_master
        interfaces:
          - network: default
      - name: fedoraKubeNodeVM
        url: https://vagrantcloud.com/tcharl/boxes/fedora-31-cgroupv1/versions/1.0.0/providers/libvirt.box
        memory_mb: 1548
        vcpus: 1
        ssh_port_on_host: 23022
        ansible_groups:
          - kube_node
        interfaces:
          - network: default
  tasks:
    - name: "Include ansible-virtualization-guest"
      import_role:
        name: "ansible-virtualization-guest"

    - name: "reloading firewalld"
      service:
        name: firewalld
        state: reloaded
      become: yes

- name: Converge
  hosts:
    - kube_master
    - kube_node
  roles:
    - role: ansible-containerization
    - { role: ansible-orchestration, become: true }
