---
- name: Converge master
  hosts:
   - kube_master
  tasks:
    - name: "Include Ansible Orchestration"
      include_role:
        name: "ansible-orchestration"
      vars:
        secure_logs: False
        preferred_nic: "eth1"
        kubernetes_allow_pods_on_master: False
        hostname: "master.osgiliath.test"
        hostname_reboot: false
        kube_firewall_zone: 'public'
        docker_install_compose: false
        company_domain: osgiliath.test
        company_realm_password: '123ADMin'
        reset_kube: True

- name: Converge node
  hosts:
   - kube_node
  tasks:
    - name: "Include Ansible Orchestration"
      include_role:
        name: "ansible-orchestration"
      vars:
        secure_logs: False
        preferred_nic: "eth1"
        hostname: "node1.osgiliath.test"
        company_domain: osgiliath.test
        company_realm_password: '123ADMin'
        hostname_reboot: false
        reset_kube: True
        kube_firewall_zone: 'public'
        nfs_mountpoints: # Mountpoints should be configured by the tcharl.ansible_volume (nfs mounts) to be available on each node
          - host: master.osgiliath.test
            mountpoints:
              - local: /net
                remote: /var/shared
                kubernetes_volumes:
                - volume_kind: Hardwire # TODO CSI
                  subtree: /artefactrepo
                  mountsize: 1
