---
dependency:
  name: galaxy
  options:
    role-file: molecule/requirements.yml
    roles-path: ../community
driver:
  name: vagrant
  provider:
    name: virtualbox
lint: yamllint . && flake8 && ansible-lint --exclude=meta
platforms:
  - name: Fedora-Molecule-Orchestration-VB
    box: fedora/33-cloud-base
    provider_options:
      cpus: 6
      memory: 8192
    provider_raw_config_args:
      - "customize ['modifyvm', :id, '--nested-hw-virt', 'on']"
      - "customize ['storagectl', :id, '--name', 'IDE', '--hostiocache', 'on']"
    interfaces:
      - auto_config: true
        network_name: private_network
        type: dhcp
      - network_name: forwarded_port
        guest: 22022
        host: 22022
      - network_name: forwarded_port
        guest: 23022
        host: 23022
    instance_raw_config_args:
      - "cache.enable :dnf"
      - "cache.auto_detect = false"
    provider_override_args:
      - "persistent_storage.enabled = true"
      - "persistent_storage.location = 'molecule-orchestration.vdi'"
      - "persistent_storage.size = 15000"
      - "persistent_storage.mount = false"
      - "persistent_storage.diskdevice = '/dev/sdb'"

provisioner:
  name: ansible
#  config_options:
#    defaults:
#      forks: 20
#      gather_timeout: 20
#      timeout: 60
#    ssh_connection:
#      pipelining: true
#      ssh_args: -o ControlMaster=auto -o ControlPersist=6000s
  env:
    ANSIBLE_ROLES_PATH: ../../..:../../../community
  inventory:
    group_vars:
      kube_master:
        kubernetes_role: master
        ns_hostname: "master.osgiliath.net"
        kubernetes_pod_network:
          cni: 'flannel'
          cidr: '10.128.0.0/16'
        hostname_reboot: false
      kube_node:
        kubernetes_role: node
        ns_hostname: "node.osgiliath.net"
        hostname_reboot: false
verifier:
  name: testinfra
  env:
    PYTHONWARNINGS: "ignore:.*U.*mode is deprecated:DeprecationWarning"
  options:
    v: 1
