---
dependency:
  name: galaxy
  options:
    role-file: molecule/requirements.yml
    roles-path: ../community
driver:
  name: vagrant
  provider:
    name: virtualbox
lint: yamllint . && flake8 && ansible-lint --exclude=meta
platforms:
  - name: Fedora-Molecule-Orchestration-VB
    box: tcharl/fedora-31-cgroupv1
    cpus: 8
    memory: 12288
    provider_raw_config_args:
      - "customize ['modifyvm', :id, '--nested-hw-virt', 'on']"
    instance_raw_config_args:
      - "vm.network :forwarded_port, guest: 22022, host: 22022, protocol: 'tcp'"
      - "vm.network :forwarded_port, guest: 23022, host: 23022, protocol: 'tcp'"
    provider_override_args:
      - "persistent_storage.enabled = true"
      - "persistent_storage.location = 'molecule-orchestration.vdi'"
      - "persistent_storage.size = 7000"
      - "persistent_storage.mount = false"
      - "persistent_storage.diskdevice = '/dev/sdb'"

provisioner:
  name: ansible
  env:
    ANSIBLE_ROLES_PATH: ../../..:../../../community
  inventory:
    links:
      group_vars: ../group_vars
verifier:
  name: testinfra
  env:
    PYTHONWARNINGS: "ignore:.*U.*mode is deprecated:DeprecationWarning"
  options:
    v: 1
