---
- name: Converge master
  hosts: master.osgiliath.test
  vars:
    secure_logs: False
    preferred_nic: "eth1"
    idm_preferred_nic: "eth1"
    kubernetes_allow_pods_on_master: False
    kube_firewall_zone: 'public'
    standalone_role: False
    reset_kube: True
  roles:
    - role: tcharl.ansible_orchestration

- name: Converge node
  hosts: node1.osgiliath.test
  vars:
    secure_logs: False
    preferred_nic: "eth1"
    master_preferred_nic: "eth1"
    kube_firewall_zone: 'public'
    reset_kube: True
    standalone_role: False
    nfs_mountpoints:
      - host: master.osgiliath.test
        mountpoints:
          - local: /net
            remote: /var/shared/volume
            kubernetes_volumes:
              - subtree: artefactrepo
                mountsize: 1
  roles:
    - role: tcharl.ansible_orchestration
