---
- name: Converge master
  hosts: kube_master
  tasks:
    - name: "Include Ansible Orchestration"
      include_role:
        name: "ansible-orchestration"
      vars:
        kubernetes_allow_pods_on_master: False
        hostname: "master.osgiliath.test"
        hostname_reboot: false
        kube_firewall_zone: 'public'
        docker_install_compose: false
        kube_alt_names:
          - "kubeadm.osgiliath.net"

- name: Converge node
  hosts: kube_node
  tasks:
    - name: "Include Ansible Orchestration"
      include_role:
        name: "ansible-orchestration"
      vars:
        hostname: "node1.osgiliath.test"
        hostname_reboot: false
        kube_firewall_zone: 'public'
