---
- name: Converge
  hosts: all
  vars:
    lvm_groups:
      - vgname: non-persistent
        disks:
          - /dev/vdb
        create: true
        lvmetanames:
          - lvname: thinpool
            size: 40%VG
            opts: "--wipesignatures y"
            create: true
            metadata: non-persistent/thinpoolmeta
            autoextendtreshold: 80
            autoextendpercent: 20
            filesystem: xfs
            mntp: /var/lib/docker
            mount: true
          - lvname: thinpoolmeta
            size: 10%VG
            opts: "--wipesignatures y"
            create: true
    libvirt_host_pools:
      - name: libvirt_vg
        type: lvm2
        source: non-persistent
    libvirt_host_networks:
      - name: default
        mode: nat
        bridge: vibr0
        ip: 192.168.122.1
        netmask: 255.255.255.0
        dhcp_start: 192.168.122.10
        dhcp_end: 192.168.122.200
    users_group_list:
      - name: libvirt
    systemusers_user_list:
      - name: libvirt
        group: libvirt
        groups: wheel
    virtualization_guest_boxes:
      - name: fedoraKubeMasterVM
        url: https://download.fedoraproject.org/pub/fedora/linux/releases/33/Cloud/x86_64/images/Fedora-Cloud-Base-Vagrant-33-1.2.x86_64.vagrant-libvirt.box
        memory_mb: 1548
        vcpus: 2 # kube min
        ssh_port_on_host: 22022
        # same as the one in molecule.yml
        ansible_groups:
          - kube_master
        interfaces:
          - network: default
      - name: fedoraKubeNodeVM
        url: https://download.fedoraproject.org/pub/fedora/linux/releases/33/Cloud/x86_64/images/Fedora-Cloud-Base-Vagrant-33-1.2.x86_64.vagrant-libvirt.box
        memory_mb: 1548
        vcpus: 2 # kube min
        ssh_port_on_host: 23022
        ansible_groups:
          - kube_node
        interfaces:
          - network: default


  tasks:
    - name: "Include ansible_virtualization_guest"
      import_role:
        name: tcharl.ansible_virtualization_guest

    - name: "reloading firewalld"
      service:
        name: firewalld
        state: reloaded
      become: yes

- name: Converge
  hosts:
    - kube_master
    - kube_node
  roles:
    - role: tcharl.ansible_containerization
    - { role: ansible-orchestration, become: true }
