---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: crbkubeadmcreatens
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-role-namespace-creator
subjects:
- kind: Group
  name: clusterAdministrators
  apiGroup: rbac.authorization.k8s.io