---
- name: Converge master
  hosts: master.osgiliath.test
  vars:
    secure_logs: False
    preferred_nic: "eth1"
    kubernetes_allow_pods_on_master: False
    kube_firewall_zone: 'public'
    standalone_role: False
    reset_kube: False
  roles:
    - role: tcharl.ansible_orchestration

- name: Converge node
  hosts: node1.osgiliath.test
  vars:
    secure_logs: False
    preferred_nic: "eth1"
    reset_kube: False
    standalone_role: False
    kube_firewall_zone: 'public'
    nfs_mountpoints:
      - host: master.osgiliath.test
        mountpoints:
          - local: /net
            mountsize: 1
            kubernetes_volumes:
              - subtree: artefactrepo
  roles:
    - role: tcharl.ansible_orchestration
