---
- name: Converge master
  hosts: master.osgiliath.test
  vars:
    secure_logs: False
    preferred_nic: "eth1"
    idm_preferred_nic: "eth1"
    master_preferred_nic: "eth1"
    kube_firewall_zone: 'public'
    reset_kube: False
    standalone_role: False
  roles:
    - role: tcharl.ansible_orchestration

- name: Converge node
  hosts: node1.osgiliath.test
  vars:
    secure_logs: False
    preferred_nic: "eth1"
    master_preferred_nic: "eth1"
    idm_preferred_nic: "eth1"
    reset_kube: False
    standalone_role: False
    nfs_mountpoints:
      - host: idm.osgiliath.test
        mountpoints:
          - remote: /var/shared/csi
            local: /net
            csi_mount: Yes
          - local: /net
            remote: /var/shared/volume
            kubernetes_volumes:
              - subtree: /artefactrepo
                mountsize: 1
  roles:
    - role: tcharl.ansible_orchestration
