---
dependency:
  name: galaxy
  enabled: ${DEPENDENCY_ENABLED:-True}
  options:
    role-file: ${REQUIREMENTS_PATH:-requirements-standalone.yml}
    roles-path: ${MOLECULE_PROJECT_DIRECTORY}/../community
    requirements-file: requirements-collections.yml
    collections-path: ${MOLECULE_PROJECT_DIRECTORY}/../community-collections
driver:
  name: vagrant
  provider:
    name: virtualbox
platforms:
  - name: master.osgiliath.test
    box: ${TESTBOX:-fedora/38-cloud-base}
    provider_options:
      cpus: 2
      memory: 2048
    interfaces:
      - auto_config: true
        network_name: private_network
        ip: "192.168.50.4"
        virtualbox__intnet: true
    groups:
      - kube_master
      - ipaclients
  - name: ipa.osgiliath.test
    box: ${TESTBOX:-fedora/38-cloud-base}
    provider_options:
      cpus: 2
      memory: 2048
    interfaces:
      - auto_config: true
        network_name: private_network
        ip: "192.168.50.6"
        virtualbox__intnet: true
    groups:
      - ipaservers
  - name: node1.osgiliath.test
    box: ${TESTBOX:-fedora/38-cloud-base}
    provider_options:
      cpus: 2
      memory: 2048
    groups:
      - kube_node
      - ipaclients
    interfaces:
      - auto_config: true
        network_name: private_network
        ip: "192.168.50.5"
        virtualbox__intnet: true
provisioner:
  name: ansible
  options:
    vvv: True
#  config_options:
#    defaults:
#      forks: 20
#      gather_timeout: 20
#      timeout: 60
#    ssh_connection:
#      pipelining: true
#      ssh_args: -o ControlMaster=auto -o ControlPersist=6000s
verifier:
  name: testinfra
  env:
    PYTHONWARNINGS: "ignore:.*U.*mode is deprecated:DeprecationWarning"
  options:
    v: 1
scenario:
  name: default_noreset_kube
  test_sequence:
    - dependency
    - cleanup
    - destroy
    - syntax
    - create
    - prepare
    - converge
    # - idempotence
    - side_effect
    - verify
    - cleanup
    - destroy
