---
- name: Debug master
  hosts: master.osgiliath.test
  tasks:
    - ansible.builtin.debug:
        var: ansible_facts

- name: Converge master
  hosts: master.osgiliath.test
  vars:
    secure_logs: False
    preferred_nic: "eth1"
    idm_preferred_nic: "eth1"
    master_preferred_nic: "eth1"
    kube_firewall_zone: 'public'
    reset_kube: True
    standalone_role: False
  #        kube_alt_names:
#          - "kubeadm.osgiliath.net"
  roles:
    - role: tcharl.ansible_orchestration

- name: Converge node
  hosts: node1.osgiliath.test
  vars:
    secure_logs: False
    preferred_nic: "eth1"
    master_preferred_nic: "eth1"
    idm_preferred_nic: "eth1"
    kube_firewall_zone: 'public'
    reset_kube: True
    standalone_role: False
    nfs_mountpoints:
      - host: master.osgiliath.test
        mountpoints:
          - local: /net
            remote: /var/shared/volume
            kubernetes_volumes:
              - subtree: artefactrepo
                mountsize: 1
  roles:
    - role: tcharl.ansible_orchestration
