---
dependency:
  name: galaxy
  enabled: ${DEPENDENCY_ENABLED:-True}
  options:
    role-file: ${REQUIREMENTS_PATH:-requirements-standalone.yml}
    requirements-file: requirements-collections.yml
    force: true
driver:
  name: vagrant
  provider:
    name: parallels
platforms:
  - name: master.osgiliath.test
    box: ${TESTBOX:-bento/fedora-42}
    provider_options:
      cpus: 2
      memory: 5120
    interfaces:
      - type: dhcp
        auto_config: true
        network_name: private_network
    groups:
      - kube_master
      - ipaclients
  - name: idm.osgiliath.test
    box: ${TESTBOX:-bento/fedora-42}
    provider_options:
      cpus: 2
      memory: 5120
    interfaces:
      - type: dhcp
        auto_config: true
        network_name: private_network
    groups:
      - ipaservers
  - name: node1.osgiliath.test
    box: ${TESTBOX:-bento/fedora-42}
    provider_options:
      cpus: 2
      memory: 5120
    interfaces:
      - type: dhcp
        auto_config: true
        network_name: private_network
    groups:
      - ipaclients
      - kube_node
provisioner:
  name: ansible
#  config_options:
#    defaults:
#      forks: 20
#   ssh_connection:
#     pipelining: true
#      ssh_args: -o ControlMaster=auto -o ControlPersist=6000s
verifier:
  name: testinfra
  env:
    PYTHONWARNINGS: "ignore:.*U.*mode is deprecated:DeprecationWarning"
  options:
    v: 1
scenario:
  name: parallels
  test_sequence:
    - dependency
    - cleanup
    - destroy
    - syntax
    - create
    - prepare
    - converge
    # - idempotence
    - side_effect
    - verify
    - cleanup
    - destroy
