---

- name: Prepare
  hosts:
    - all
  tasks:
    - name: "install fedora ansible prerequisites"
      ansible.builtin.raw: dnf install -y python3 python3-libdnf5
      changed_when: false
      become: true
    - include_role:
        name: tcharl.ansible_orchestration
        tasks_from: requirements.yml
      vars:
        secure_logs: False
        preferred_nic: "eth1"
        idm_preferred_nic: "eth1"
        company_domain: osgiliath.test
        company_realm_password: '123ADMin'
        company_ad_password: '123ADmPass'
        nfs_mountpoints:
          - host: master.osgiliath.test
            mountpoints:
              - local: /net
                expose_kube_volume: True
                mountsize: 1
